import Foundation

/// IANA's list of top-level domains, which is what makes "scheme-less domains including newer TLDs"
/// (FLT-2) a decidable question rather than a guess about what looks like a host.
///
/// It is a bundled file regenerated by `Scripts/update-tld-list.sh` and never fetched at runtime: the
/// analyser runs inside a 20 ms stage, and the app makes no network call to decide what is on the
/// user's screen.
public struct TopLevelDomains: Sendable, Equatable {
    private let names: Set<String>
    /// IANA's own version line, kept so that the inspector and a bug report can say how old the list is.
    public let version: String?

    public init(names: some Sequence<String>, version: String? = nil) {
        self.names = Set(names.map { $0.lowercased() })
        self.version = version
    }

    public var count: Int { names.count }

    /// - Parameter label: The last label of a host, already punycoded — `xn--p1ai`, not `рф`. The list
    ///   is in punycode and comparing anything else against it would answer no for every IDN.
    public func contains(_ label: String) -> Bool {
        names.contains(label.lowercased())
    }

    public static let fileName = "top-level-domains.txt"

    public static func bundled(in bundle: Bundle) throws -> TopLevelDomains {
        guard let url = bundle.url(forResource: "top-level-domains", withExtension: "txt") else {
            throw CocoaError(.fileNoSuchFile)
        }
        return try load(from: url)
    }

    public static func load(from url: URL) throws -> TopLevelDomains {
        parse(try String(contentsOf: url, encoding: .utf8))
    }

    /// One name per line; `#` starts a comment, and IANA's version line is kept as the version.
    public static func parse(_ contents: String) -> TopLevelDomains {
        var names: [String] = []
        var version: String?
        for line in contents.split(separator: "\n", omittingEmptySubsequences: true) {
            let line = line.trimmingCharacters(in: .whitespaces)
            if line.hasPrefix("#") {
                if version == nil, line.contains("Version") { version = String(line.dropFirst()).trimmingCharacters(in: .whitespaces) }
                continue
            }
            guard !line.isEmpty else { continue }
            names.append(line)
        }
        return TopLevelDomains(names: names, version: version)
    }

    /// What the analyser uses when the bundled file cannot be read.
    ///
    /// Empty, so a missing list means no scheme-less domain is detected. The alternative — treat any
    /// two-label token as a host — would turn `Info.plist`, `README.txt` and `v2.0` into links in
    /// every selection on the Mac, which is the failure this list exists to prevent. It does not
    /// prevent all of them: `.md` and `.sh` are real top-level domains, so a bare `notes.md` is a
    /// domain to any list-based detector, PopClip's included. `ContentAnalyzer` narrows that by
    /// claiming file paths first.
    public static let none = TopLevelDomains(names: [])
}
