#!/bin/bash
# Regenerates Resources/top-level-domains.txt from IANA's published list (FLT-2).
#
# "Scheme-less domains including newer TLDs" is the requirement, and the only way to know what a TLD
# is, is to be told. The file is data and is regenerated deliberately, never fetched at runtime: the
# analyser runs inside a 20 ms stage and the app makes no network call to decide what a selection is.
#
# Run it when a release is being prepared, and commit the result with its version line.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/Resources/top-level-domains.txt"
SOURCE="https://data.iana.org/TLD/tlds-alpha-by-domain.txt"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

curl -fsS --max-time 60 "$SOURCE" -o "$TMP"

# IANA ships the names in upper case with a version comment on the first line. We keep the comment,
# because it is the only provenance the file has, and lower-case the names because that is how they
# are compared. IDN TLDs stay in their punycode form; the analyser punycodes before it looks.
{
  echo "# Generated by Scripts/update-tld-list.sh from $SOURCE"
  grep '^#' "$TMP" | head -1
  grep -v '^#' "$TMP" | tr '[:upper:]' '[:lower:]' | grep -v '^$' | sort
} > "$OUT"

echo "$(grep -vc '^#' "$OUT") top-level domains written to ${OUT#"$ROOT"/}"
